version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: blog_cc_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: blogcc
      POSTGRES_PASSWORD: blogpassword
      POSTGRES_DB: blogdbcc
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
